# example config file
# server config >>>
server-port: ":8080"
proxy: true
trusted-proxies:
  - "127.0.0.0/8"
  - "192.168.0.0/16"
  - "172.16.0.0/12"
  - "10.0.0.0/8"
# database config >>>
db-username: "root"
db-password: "passwd"
db-database: "info2021"
# "db-hostname: 127.0.0.1" & "port: 3306" can be omitted
# db-hostname: 127.0.0.1
# db-port: 3306
# excel keys >>>
excel:
  name: "姓名"
  id: "证件号"
  campus: "校区"
  faculty: "学院"
  class: "班级"
  uid: "学号"
  house: "楼号"
  room: "寝室"
  bed: "床"
