# example config file
# server config >>>
server-port: ":8080"
# database config >>>
db-username: "root"
db-password: "passwd"
db-database: "info_test"
# "db-hostname: 127.0.0.1" & "port: 3306" can be omitted
# db-hostname: 127.0.0.1
# db-port: 3306